### ISSUE TITLE
service unavailable

### ISSUE THREAD

**Issue by andreacorleto** [up2university/kuboxed#23] opened 2018-11-20 10:43 UTC
![cern_service_unavailable](https://user-images.githubusercontent.com/36439670/48768474-67d64280-ecb9-11e8-9d83-43229aaf7f82.jpg)

**Comment by michzimny** [comment] 2018-11-20 10:54
Which instance is that? Please provide URL address. It seems both instances are working for me right now (apart from issue #21).

**Comment by andreacorleto** [comment] 2018-11-20 11:02
https://cernbox.test.up2university.eu/cernbox/index.php/apps/files/?dir=/&view=sharingout

**Comment by michzimny** [comment] 2018-11-20 12:25
@diocas, this link works for me and does not work for @andreacorleto. What can be the cause? Related to #21 (which still persists)?

**Comment by michzimny** [comment] 2018-11-21 22:39
@andreacorleto, please have a look if the issue still persists.

**Comment by diocas** [comment] 2018-11-22 12:55
I would have to look into the logs, I cannot tell by that error.

**Comment by andreacorleto** [comment] 2018-11-22 13:05
@michzimny @diocas yes, the error still persists

**Comment by andreacorleto** [comment] 2018-11-23 09:09
To better describe the error: when I click on a file shared or try to download it I got this error. They are mp4 files. Even if I try to delete these files I got an error and deleting it's not allowed. I cannot even upload other files due to issue #21

**Comment by ebocchi** [comment] 2018-11-26 14:00
Ciao @andreacorleto,
from the messages above I do not understand if CERNBox does not work *at all* for you or only when you try to perform some sort of operations on some files.
Could you please clarify this, please?

In the meantime, I am having a look in the logs server side

**Comment by andreacorleto** [comment] 2018-11-26 14:15
Ciao @ebocchi 
I don't know how and why but today everything works fine for me in CERNBox.
During the last week, I had problems in download and upload files due to issue #21 and #23. But now everything seems to be fine. 
Thanks

**Comment by michzimny** [comment] 2018-11-26 15:07
@ebocchi, today in the morning, I have killed cernbox and cernbox-gateway pods, because #21 appeared again. Perhaps, my activity solved the both issues. 

However earlier, on 21 Nov, I did the same, and then #21 was solved, but @andreacorleto reported soon (22 Nov) that this issue #23 still persists for him. So, I don't know how they are related.

If you were able to find out anything more from the logs, then it would be beneficial for the future.

**Comment by ebocchi** [comment] 2018-11-26 15:11
Ciao @andreacorleto,
Digging in the logs, there were some "operation not permitted" errors on the storage backend.
This is quite strange as, according to the LDAP entries, you are the owner of those files.

I guess this was a glitch between CERNBox and the storage backend.
I saw that the CENRBox containers were restarted 2 hours ago and this likely fixed the permission error.
This is reinforced by you reporting that the issue is now solved.

I am closing this issue now.
Should this re-appear, do not hesitate to reopen this issue or open a new one.
Thanks!

**Closed as completed** 2018-11-26 15:11 UTC
